# Generated by Django 4.2.9 on 2024-01-15 08:28

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bidder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('allowed_max_bid', models.CharField(max_length=255)),
                ('bidder_type', models.CharField(choices=[('admin', 'Admin'), ('dealer', 'Dealer')], default='dealer', max_length=10)),
                ('copart_accounts', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Copart_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('member_number', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lot', models.CharField(max_length=255)),
                ('VIN', models.CharField(max_length=30)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_status', models.CharField(choices=[('winning', 'WINNING'), ('outbid', 'OUTBID'), ('won', 'WON')], default='winning', max_length=10)),
                ('username', models.CharField(max_length=255)),
                ('bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='api.bidder')),
            ],
        ),
    ]
