# Generated by Django 4.2.9 on 2024-01-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidder',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
